const {test}=require('node:test'),assert=require('node:assert/strict');
const {Landing,shore}=require('./arrival-physics.js');
function run(g,s,input={x:0,y:0}){for(let i=0;i<Math.round(s*60);i++)g.advance(1/60,input);}
function shoreGame(x=450){const g=new Landing();Object.assign(g.canoe,{x,y:shore(x)+28,vx:0,vy:0});run(g,.05);return g;}
test('canoe glides, steers and back-paddles rather than jumping between destinations',()=>{const g=new Landing();run(g,1,{x:0,y:-1});const y=g.canoe.y;assert.ok(g.canoe.vy<-30);run(g,.3);assert.ok(g.canoe.y<y);run(g,.8,{x:1,y:0});assert.ok(g.canoe.th>.2);const speed=Math.hypot(g.canoe.vx,g.canoe.vy);run(g,.3,{x:0,y:1});assert.ok(Math.hypot(g.canoe.vx,g.canoe.vy)<speed);});
test('high-speed landing visibly impacts and wets cargo, slow approach can settle',()=>{const g=shoreGame();g.canoe.vy=-110;run(g,.2);assert.ok(g.bumps>0);assert.ok(g.items[0].wet>0);const s=shoreGame();run(s,1);assert.equal(s.bumps,0);assert.ok(s.canExit());});
test('exposed rocks deflect the hull and do not destroy or trap it',()=>{const g=new Landing();Object.assign(g.canoe,{x:310,y:560,vy:-90});run(g,.7);assert.ok(g.bumps>0);assert.ok(Number.isFinite(g.canoe.x));assert.ok(g.canoe.y>500);});
test('more than one shoreline angle allows a physical landing',()=>{for(const [x,th]of [[405,-.45],[525,.6]]){const g=shoreGame(x);g.canoe.th=th;run(g,.5);assert.ok(g.canExit());g.interact();assert.equal(g.mode,'walk');assert.ok(g.player.y<shore(g.player.x));}});
test('gear unloads, follows a walking camper, slows bulky carrying and drops anywhere',()=>{const g=shoreGame();g.interact();g.refreshContext();assert.equal(g.near.type,'gear');g.interact();const id=g.carry;assert.ok(id);assert.equal(g.items.find(i=>i.id===id).inBoat,false);run(g,1,{x:0,y:-1});const y=g.player.y;g.interact();assert.equal(g.carry,null);const item=g.items.find(i=>i.id===id);assert.ok(item.y<shore(item.x)-10);run(g,.4,{x:1,y:0});assert.ok(Math.abs(item.y-y)<8);});
test('waves wet and shift exposed gear; high ground remains dry',()=>{const g=shoreGame();g.mode='walk';const [a,b]=g.items;a.inBoat=b.inBoat=false;Object.assign(a,{x:430,y:shore(430)+7});Object.assign(b,{x:500,y:shore(500)-60});const x=a.x;run(g,6);assert.ok(a.wet>20);assert.ok(a.x>x+5);assert.equal(b.wet,0);});
test('unsecured hull visibly drifts; a dry bow-line restrains it',()=>{const g=shoreGame();g.mode='walk';const c=g.canoe;c.y=shore(c.x)+65;const x=c.x;run(g,7);assert.ok(c.x>x+4);const b=g.bow();c.tie=1;c.anchor={x:b.x,y:b.y-23};const start={x:c.x,y:c.y};run(g,8);assert.ok(Math.hypot(c.x-start.x,c.y-start.y)<15);});
test('bow towing moves and rotates the hull; hold ties once without repeated taps',()=>{const g=shoreGame();g.interact();g.carry='canoe';const y=g.canoe.y;run(g,3,{x:.5,y:-1});assert.ok(g.canoe.y<y-10);assert.ok(Math.abs(g.canoe.th)>.02);g.press();run(g,1.5);g.release();assert.equal(g.canoe.tie,1);assert.equal(g.carry,null);});
test('offshore hold cannot fabricate a dry anchor',()=>{const g=shoreGame();g.mode='walk';g.carry='canoe';g.player.y=shore(g.player.x)+25;g.press();run(g,2);g.release();assert.equal(g.canoe.tie,0);});
test('completion depends on actual settled conditions, not order or matching destinations',()=>{const g=shoreGame();g.mode='walk';g.canoe.y=shore(g.canoe.x)-90;for(const [i,item]of g.items.entries())Object.assign(item,{inBoat:false,x:350+i*80,y:260});run(g,3);assert.equal(g.complete,false);run(g,2);assert.equal(g.complete,true);});
test('cancel/pause preserve gear and prevent latent holds or drift',()=>{const g=shoreGame();g.interact();g.interact();const carry=g.carry;g.press();g.cancelInput();assert.equal(g.carry,carry);assert.equal(g.actionHeld,false);g.paused=true;const before=JSON.stringify(g);run(g,3,{x:1,y:0});assert.equal(JSON.stringify(g),before);});
test('floating gear and hull stay recoverable in the shoreline eddy',()=>{const g=shoreGame();g.mode='walk';g.canoe.y=shore(g.canoe.x)+100;const a=g.items[0];Object.assign(a,{inBoat:false,x:450,y:shore(450)+90});run(g,80);assert.ok(g.depth(g.canoe.x,g.canoe.y)<130);assert.ok(g.depth(a.x,a.y)<105);});
test('paddle force cannot drive a canoe uphill through the campsite',()=>{const g=shoreGame();run(g,12,{x:0,y:-1});assert.ok(g.points().every(p=>g.depth(p.x,p.y)>-43));});
test('bow can be taken before unloading and floating hull can be boarded again',()=>{const g=shoreGame();g.interact();assert.ok(g.items.every(i=>i.inBoat));assert.equal(g.grabBow(),true);assert.equal(g.carry,'canoe');g.interact();assert.equal(g.board(),true);assert.equal(g.mode,'paddle');assert.ok(g.items.every(i=>i.inBoat));});
test('carrying a bulky pack slows walking while remaining responsive',()=>{const a=shoreGame(),b=shoreGame();for(const g of [a,b]){g.mode='walk';g.player.x=450;g.player.y=260;}b.carry='pack';b.items[0].inBoat=false;run(a,.7,{x:1,y:0});run(b,.7,{x:1,y:0});assert.ok(a.player.x>b.player.x+20);assert.ok(b.player.x>490);});
test('fixed-step landing results agree at different rendering rates',()=>{const cases=[30,60,120].map(hz=>{const g=new Landing();for(let i=0;i<hz*3;i++)g.advance(1/hz,{x:0,y:-1});return g;});for(const g of cases.slice(1)){assert.ok(Math.abs(g.canoe.y-cases[0].canoe.y)<.1);assert.equal(g.bumps,cases[0].bumps);}});
